name: No Response

on:
    issue_comment:
        types: [created]

jobs:
    noResponse:
        runs-on: ubuntu-latest
        steps:
            - uses: lee-dohm/no-response@v0.5.0
              with:
                  token: ${{ github.token }}
